### ISSUE TITLE
text-to-speech.html is using watson-token as a query parameter

### ISSUE THREAD

**Issue by mangelcalvo** [watson-developer-cloud/speech-javascript-sdk#101]
When trying the text-to-speech.html example, the html page sends a GET request to get the audio file by using
https://stream-fra.watsonplatform.net/text-to-speech/api/v1/synthesize?text=Hello from IBM Watson&watson-token=eyJraWQiOiIyMDE3MTAzMC0...

The service is answering with a 401 Unauthorized response. The watson-token is deprecated so that seems the reason for the issue.

How can a URL request be sent to the service ?

**Comment by dpopp07** [comment]
Is the service authenticated using IAM tokens? If so, you can use `access_token` as your parameter to pass in the token with and that should solve the problem.

**Comment by w0o** [comment]
This is related to the recent #112 I opened and will be fixed with that PR, unfortunately the suggested instructions will not work. @mangelcalvo hold on for a bit, I will try and get this done by tomorrow!

**Comment by germanattanasio** [comment]
@w0o was this fixed with your PR?

**Comment by w0o** [comment]
That PR supports using the access-token for the region from the server-side, but I just checked and it seems bower actually installs an older version of the javascript which still does not contain the fix for allowing to pass the access_token parameter instead of watson-token.
@germanattanasio  Can you please take a look why the examples `npm install` (actually it is `postinstall` that runs) still puts the old version under static/bower_components ?

**Comment by joyychang** [comment]
The source of the dependency problem seems to be that we are using '*' as version in `package.json` while it does translate to a specific version in `package-lock.json`. This can be alleviated by not checking in the lock file.
In the same area of concern, we attempt to do a green-blue deployment of the example prior to new version of `watson-speech` being released, resulting in our example never using the current release of the module.
To wait for blue-green deploy before doing sementic-release while deployment depend on new release to be cut seems to be a catch 22 situation.

@germanattanasio thoughts?

**Comment by germanattanasio** [comment]
we need to first do the semantic release and then do the blue-green deployment

**Comment by w0o** [comment]
@joyychang, @germanattanasio  I totally agree with the blue-green deployment being an issue yet this issue is also happening in a local testing since bower is getting the wrong version each and every time. We must ensure bower also gets the latest version or better yet, let bower collect a local build (makes sense for local testing too).

Aside, I think we should stop using both bower and npm modules due to the redundancy and also to avoid those kind of collisions & release synchronization issues. 
It looks as if a simple npm script command or an updated webpack config do exactly what bower is doing now thus bower can be completely replaced by npm and make the examples more reliable. I can help with the migration if the team agrees with this.

**Comment by dpopp07** [comment]
I also feel that using both `npm` and `bower` is redundant and have had to wrestle a lot with the problem you are describing - just haven't had time to look at it.  Unless @germanattanasio has a specific reason he wants to be using `bower`, I am in support of consolidating down to one package manager and would welcome your help!

**Comment by germanattanasio** [comment]
I don't mind removing `bower`. 
@w0o can you help with a PR?

**Comment by adamj9431** [comment]
Looks like all the demos are currently broken. Changing `token` to `access_token` in the demo code fixes them

**Comment by w0o** [comment]
@germanattanasio I will take this one and make a PR.
@adamj9431 Totally understandable considering that CF credentials have been completely deprecated. Maybe we should just update the entire the code to use IAM access tokens.

**Comment by germanattanasio** [comment]
This should be working now.

**Comment by w0o** [comment]
Confirmed this to be working in the samples and already in a few other projects.
